# Generated by Django 5.2.17 on 2026-08-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=255, unique=True)),
                ('requests_per_second', models.FloatField()),
                ('burst_size', models.IntegerField()),
                ('mode', models.CharField(choices=[('token_bucket', 'Token Bucket'), ('sliding_window', 'Sliding Window')], default='token_bucket', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
